# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: icon-pack.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ficon-pack.proto"}\n\x08IconPack\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x1d\n\x05icons\x18\x04 \x03(\x0b\x32\x0e.IconPack.Icon\x1a"\n\x04Icon\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x62\x06proto3'
)


_ICONPACK = DESCRIPTOR.message_types_by_name["IconPack"]
_ICONPACK_ICON = _ICONPACK.nested_types_by_name["Icon"]
IconPack = _reflection.GeneratedProtocolMessageType(
    "IconPack",
    (_message.Message,),
    {
        "Icon": _reflection.GeneratedProtocolMessageType(
            "Icon",
            (_message.Message,),
            {
                "DESCRIPTOR": _ICONPACK_ICON,
                "__module__": "icon_pack_pb2"
                # @@protoc_insertion_point(class_scope:IconPack.Icon)
            },
        ),
        "DESCRIPTOR": _ICONPACK,
        "__module__": "icon_pack_pb2"
        # @@protoc_insertion_point(class_scope:IconPack)
    },
)
_sym_db.RegisterMessage(IconPack)
_sym_db.RegisterMessage(IconPack.Icon)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ICONPACK._serialized_start = 19
    _ICONPACK._serialized_end = 144
    _ICONPACK_ICON._serialized_start = 110
    _ICONPACK_ICON._serialized_end = 144
# @@protoc_insertion_point(module_scope)
